apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: angular-ndbx-template
  title: Angular with Allianz NDBX Template
  description:
    This template includes an Angular App with the Allianz NDBX Angular library
  tags:
    - recommended
    - angular
    - ndbx
spec:
  templater: cookiecutter
  type: website
  path: '.'
  schema:
    required:
      - component_id
      - description
    properties:
      component_id:
        title: Name
        type: string
        description: Unique name of the component
      description:
        title: Description
        type: string
        description: Description of the component
